### ISSUE TITLE
如何打印浏览器页面

### ISSUE THREAD

**Issue by letsoon** [letsoon/letsoon.github.io#5]
### 制作A4纸尺寸页面模板
```
A4纸尺寸：210 毫米 / 297 毫米
转换为模板尺寸（px）：width / (297 / 210) * width   //注意小数部分处理是向上取整
例如模板宽度是795px：795px / (297 / 210) * 795 = 1124.357142857143 ≈ 1125px
```
[在线效果预览](https://codepen.io/letsoon/pen/MWaJvQm)

>html代码
```html
<button onclick='window.print()'>打印</button>
  <div class="page">
    <section>
      <div class="content">
      </div>
      <p class="footer">第 1 页 共 3 页</p>
    </section>
    <section>
      <div class="content">
      </div>
      <p class="footer">第 2 页 共 3 页</p>
    </section>
    <section>
      <div class="content">
      </div>
      <p class="footer">第 3 页 共 3 页</p>
    </section>
  </div>
```
>样式设置
```css
  <style>
    //清除浏览器默认样式
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      background: #666666;
    }
    //打印按钮
    button {
      position: fixed;
      top: 5px;
      left: calc(50vw + 400px);
      padding: 5px;
    }
    //打印容器
    .page {
      width: 795px;
      margin: auto;
      background: white;
      position: relative;
    }
    //页面容器
    section {
      width: 100%;
      height: 1125px;
      break-after: page;
      padding: 2cm;
      position: relative;
      background: white;
    }
    //内容区域
    section .content {
      overflow: hidden;
      width: 100%;
      height: 100%;
      background: #eeeeee;
    }
    //页码样式，需要自行调整
    section p.footer {
      font-size: 14px;
      position: absolute;
      bottom: 0.95cm;
      left: 0;
      right: 0;
      text-align: center;
    }
    //页面分割样式
    section::after {
      display: block;
      content: "";
      position: absolute;
      left: 0;
      bottom: 0;
      width: 795px;
      background: #666666;
      height: 20px;
    }

    @media print {
     //隐藏不需要打印的元素
      button,
      section::after {
        display: none;
      }

      @page {
        margin: 0;  //禁用页眉页脚选项
        size: a4;  //禁用打野尺寸设置
      }
    }
  </style>
```
